-- 0015_station_licenses.sql — lab codes («منظومة الرموز»): one code per lab, bound to one
-- device on first use, valid for duration_days from that activation, with the stations
-- (and the full admin panel) it may open. The code is stored only as a hash.
-- The app also creates these tables on first use, so existing databases need no manual step.

create table if not exists station_licenses (
  id            text primary key,
  code_hash     text unique not null,
  code_hint     text not null default '',
  lab_name      text not null,
  note          text not null default '',
  duration_days integer not null,
  modules       text not null default '[]',   -- JSON array of module ids
  status        text not null default 'active', -- active | stopped
  device_id     text,
  device_label  text,
  activated_at  bigint,                          -- ms since epoch
  expires_at    bigint,
  last_seen_at  bigint,
  created_at    bigint not null
);

-- Signing key for device licenses (generated by the app) and the contact line.
create table if not exists license_config (
  key   text primary key,
  value text not null default ''
);
